
@url = http://localhost:3001

@AccessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InR1bmdAZ21haWwuY29tIiwic3ViIjoiYzA2ZmZjOGYtYWVhMi00MDIyLTg2YWYtYTM5ZGEzN2E3NDJiIiwiaWF0IjoxNzU0MTQ5ODY1LCJleHAiOjE3NTQyMzYyNjV9.v3tIgJMM3T8CHOBSBvgEzP7xjPLzKfyY7hd-1poW7YQ


### get all classes
GET {{url}}/classes
Content-Type: application/json
Authorization: Bearer {{AccessToken}}

### get a class by id
GET {{url}}/classes/c84eb874-1eb5-43dc-85e7-2c2fa0631a7c
Content-Type: application/json
Authorization: Bearer {{AccessToken}}


### Create class
POST {{url}}/classes
Content-Type: application/json
Authorization: Bearer {{AccessToken}}

{
  "name": "Tiếng Anh",
  "prompt": "Tôi muốn học tiếng anh, trình độ trung bình, tôi là học sinh lớp 9 tại Việt Nam, mong muốn cải thiện tiếng anh để thi vào cấp 3"
}

### update class
PATCH {{url}}/classes/c84eb874-1eb5-43dc-85e7-2c2fa0631a7c
Content-Type: application/json
Authorization: Bearer {{AccessToken}}

{
  "name": "Tiếng Anh "
}

### delete class
DELETE {{url}}/classes/69762b8c-cae1-42c0-af78-55def370d0cd
Content-Type: application/json
Authorization: Bearer {{AccessToken}}