@url = http://localhost:3001

@AccessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InR1bmdAZ21haWwuY29tIiwic3ViIjoiYzdlYWM0YTAtMDQxNy00YzM4LThlZjAtZjU2MTZlYzZiNTRhIiwiaWF0IjoxNzUzODg2NTI3LCJleHAiOjE3NTM5NzI5Mjd9.bbhB9UbQELuMyuZ8l4nGg1ZCFeACirA3soPIzIftoLU



### get one knowledge by id
GET {{url}}/knowledges/detail/502db7c2-f9a1-4ebf-b44d-60ae8763c87a
Content-Type: application/json
Authorization: Bearer {{AccessToken}}


### get a knowledge of topic by id
GET {{url}}/knowledges/topic/ec5e4825-3562-47ea-9733-ecce199ae817
Content-Type: application/json
Authorization: Bearer {{AccessToken}}


### create a new knowledge 
POST {{url}}/knowledges
Content-Type: application/json
Authorization: Bearer {{AccessToken}}

{
  "name":"danh từ",
  "content": "danh từ đếm được",
  "topicId": "9e72585b-9455-4979-ac2b-26c1edb2a412"
}

### generate knowledge
POST {{url}}/knowledges/topic/ec5e4825-3562-47ea-9733-ecce199ae817/generate?maxTokens=10000&temperature=0.5
Authorization: Bearer {{AccessToken}}
