@url = http://localhost:3001

@AccessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InR1dHR1eHl0aW5AZ21haWwuY29tIiwic3ViIjoiMjMzYWM3OTItYmMyNi00MDlhLTkwYmYtNTZkODM0OTQzZmJhIiwiaWF0IjoxNzUzNzYxMjg4LCJleHAiOjE3NTM4NDc2ODh9.nv0F8vkDzAyw9yRnk9UNPO5b7AZrsB_NIg3tXTsbfEE


### get a topic by id
GET {{url}}/topics/b7bb1025-b2a5-4a2c-9ad7-260c04169d49
Content-Type: application/json
Authorization: Bearer {{AccessToken}}


### get all topics
GET {{url}}/topics
Content-Type: application/json
Authorization: Bearer {{AccessToken}}

### create a new topic
POST {{url}}/topics
Content-Type: application/json
Authorization: Bearer {{AccessToken}}

{
  "name": "Tiếng Anh cơ bản",
  "description": "Học tiếng anh cơ bản",
  "prompt": "Hãy giúp tôi học tiếng anh cơ bản"
}

### edit a topic
PATCH {{url}}/topics/b86f20e5-816a-4541-b1a8-8ccd286b27c5
Content-Type: application/json
Authorization: Bearer {{AccessToken}}

{
  "name": "Toán cơ bản"
}

### delete a topic
DELETE {{url}}/topics/b86f20e5-816a-4541-b1a8-8ccd286b27c5
Content-Type: application/json
Authorization: Bearer {{AccessToken}}


