@url = http://localhost:3001

### Register a new user
POST {{url}}/auth/register
Content-Type: application/json

{
  "email":"tung@gmail.com",
  "password":"Tt123456@",
  "name":"Tung"
}

### Login a user
POST {{url}}/auth/login
Content-Type: application/json

{
  "email":"tung@gmail.com",
  "password":"Tt123456@"
}

### refresh token
POST {{url}}/auth/refresh
Content-Type: application/json

### logout
POST {{url}}/auth/logout
